### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by claraj** [brendon21c/lmn#24] opened 2017-04-13 17:33 UTC
Traceback (most recent call last):
  File "../LMNOPproject/lmn/ticketmaster.py", line 129, in get_dates_for_artist
    artist = Artist.objects.create(name = name)
  File "/Users/admin/Documents/StudentProjectsTemp/lmn/venv/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/admin/Documents/StudentProjectsTemp/lmn/venv/lib/python3.5/site-packages/django/db/models/query.py", line 393, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/admin/Documents/StudentProjectsTemp/lmn/venv/lib/python3.5/site-packages/django/db/models/base.py", line 804, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/admin/Documents/StudentProjectsTemp/lmn/venv/lib/python3.5/site-packages/django/db/models/base.py", line 834, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/admin/Documents/StudentProjectsTemp/lmn/venv/lib/python3.5/site-packages/django/db/models/base.py", line 920, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/admin/Documents/StudentProjectsTemp/lmn/venv/lib/python3.5/site-packages/django/db/models/base.py", line 959, in _do_insert
    using=using, raw=raw)
  File "/Users/admin/Documents/StudentProjectsTemp/lmn/venv/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/admin/Documents/StudentProjectsTemp/lmn/venv/lib/python3.5/site-packages/django/db/models/query.py", line 1060, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/admin/Documents/StudentProjectsTemp/lmn/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/Users/admin/Documents/StudentProjectsTemp/lmn/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/admin/Documents/StudentProjectsTemp/lmn/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/admin/Documents/StudentProjectsTemp/lmn/venv/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/admin/Documents/StudentProjectsTemp/lmn/venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/admin/Documents/StudentProjectsTemp/lmn/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "lmn_artist_pkey"
DETAIL:  Key (id)=(1) already exists.

**Comment by marie8bit** [comment] 2017-04-13 20:08
can't reproduce this error. pretty sure it was fixed with page redirect issue

**Closed as completed by marie8bit** 2017-04-13 20:08 UTC
